/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e57ff1ff-ca46-4831-9a89-d3e0980b5fda",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_sqYupfkdj",
    "aws_user_pools_web_client_id": "6naac6pltl9t901flmbh5cvqhs",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wahwjwpghbda7fcsvoapp7javq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b3unkox2rbejngs6aiaawfboxu"
};


export default awsmobile;
